# Generated by Django 3.0.4 on 2020-03-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='css_file',
            field=models.FileField(blank=True, upload_to='js_projects/<django.db.models.fields.SlugField>/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='html_file',
            field=models.FileField(upload_to='js_projects/<django.db.models.fields.SlugField>/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='js_file',
            field=models.FileField(upload_to='js_projects/<django.db.models.fields.SlugField>/%Y/%m/%d/'),
        ),
    ]
