# Generated by Django 3.0.4 on 2020-03-11 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('js_projects', '0002_auto_20200311_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='css_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='html_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='js_file',
        ),
        migrations.AddField(
            model_name='project',
            name='css_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='html_code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='js_code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
